### PR TITLE
otherwise it's not working correct... pls. check

### PR DESCRIPTION
**Pull request by philippfrenzel**
check if this is needed

### CODE REVIEW

**Comment by schmunk42** [comment]
Hmm, I don't think so. The tests failed, and also [the docs](https://github.com/vlucas/phpdotenv#usage) from dotenv state that the current syntax should be right.
Which dotenv version are you using? They released a 2.* a while ago.

**Comment by philippfrenzel** [comment]
ok maybe it's something within my php version? I think i need to learn how to setup the docker env... Thanks for taking a look at it!

**Comment by schmunk42** [comment]
Which error do you get?

**Comment by philippfrenzel** [comment]
Actually it says can’t find

Dotenv\Dotenv()

Class not found …

If I just write it as I uploaded it, it works… So don’t know how to fix it…?

**Comment by schmunk42** [comment]
Can you post the output of `php -v` and `composer show -i`?

**Comment by philippfrenzel** [comment]
Philipps-MacBook-Pro:app philippfrenzel$ php -v
PHP 5.6.13 (cli) (built: Sep 14 2015 11:14:19) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans


Philipps-MacBook-Pro:app philippfrenzel$ composer show -i
2amigos/yii2-highcharts-widget            dev-master ff3e2f5 Highcharts JS widget for Yii2.
2amigos/yii2-leaflet-extension            dev-master d517285 LeafLet Mobile-Friendly Interactive Maps Extension Library for Yii2.
2amigos/yii2-leaflet-makimarker-plugin    dev-master 0a00ef8 Yii2 Leaflet plugin to create map icons using Maki Icons from MapBox.
2amigos/yii2-leaflet-markercluster-plugin dev-master 41d9376 Yii2 LeafLet Plugin to provide beautiful, sophisticated, high performance marker clustering solution with smooth animations and lots of...
almasaeed2010/adminlte                    v2.3.0             AdminLTE - admin control panel and dashboard that's based on Bootstrap 3
anthonymartin/geo-location                v1.0.0             Retrieve bounding coordinates, distances, longitude and latitude with GeoLocation.class.php
bower-asset/autosize                      2.0.0              Autosize is a small, stand-alone script to automatically adjust textarea height to fit text.
bower-asset/backbone                      1.2.3              
bower-asset/bootstrap                     v3.3.5             The most popular front-end framework for developing responsive, mobile first projects on the web.
bower-asset/fullcalendar                  v2.3.2             Full-sized drag & drop event calendar
bower-asset/highcharts-release            v4.1.4             
bower-asset/jquery                        2.1.4              
bower-asset/jquery-cookie                 dev-master d72bb07 
bower-asset/jquery-ui                     1.11.4             
bower-asset/jquery.inputmask              3.1.63             jquery.inputmask is a jquery plugin which create an input mask.
bower-asset/js-cookie                     v1.5.1             
bower-asset/jsoneditor                    v3.2.0             A web-based tool to view, edit and format JSON
bower-asset/leaflet                       v0.7.5             JavaScript library for mobile-friendly interactive maps
bower-asset/modernizr                     v2.8.3             
bower-asset/moment                        dev-master f3fbef9 
bower-asset/pnotify                       2.0.1              JavaScript notification plugin.
bower-asset/punycode                      v1.3.2             
bower-asset/slidebars                     0.10.3             
bower-asset/typeahead.js                  v0.11.1            
bower-asset/underscore                    1.8.3              
bower-asset/vis                           dev-master 111c998 A dynamic, browser-based visualization library.
bower-asset/yii2-pjax                     dev-master 3f20897 
cboden/ratchet                            v0.3.3             PHP WebSocket library
cebe/js-search                            dev-master ca1a1d0 A client side search engine for use on static pages.
cebe/markdown                             1.0.x-dev f681fee  A super fast, highly extensible markdown parser for PHP
cebe/markdown-latex                       dev-master 9c4351e A super fast highly extensible markdown parser for PHP that converts markdown files into latex
cebe/yii2-gravatar                        1.1                Gravatar Widget for Yii 2
codemix/yii2-localeurls                   1.2.7              Automatic locale/language management for URLs.
codemix/yii2-streamlog                    dev-master 8a0f039 A Yii 2 log target for streams in URL format
creocoder/yii2-nested-sets                0.9.0              The nested sets behavior for the Yii framework
cybercog/yii2-google-analytics            0.3.1              Google Analytics extension for the Yii2 framework
dektrium/yii2-rbac                        dev-master 41a5c26 RBAC management module for Yii2
dektrium/yii2-user                        v0.9.4             Flexible user registration and authentication module for Yii2
devgroup/yii2-jsoneditor                  v1.0.0             Yii2 jsoneditor widget
dmstr/yii2-adminlte-asset                 2.2.1              Backend theme for Yii2 Framework
dmstr/yii2-app-command                    dev-master 41f2815 Console command for Yii 2 Framework to manage your application source code and configuration settings
dmstr/yii2-application-metadata           dev-master 3c56fe2 Provides in-depth configuration and application information
dmstr/yii2-bootstrap                      dev-master 96d5561 yii2 bootstrap components and extensions from diemeisterei GmbH
dmstr/yii2-cms-dev-metapackage            dev-master 801b653 Content Management Development Extensions for Phundament 4 (Yii 2.0 Framework)
dmstr/yii2-cms-metapackage                dev-master 5bf8477 Content Management Extensions for Phundament 4 (Yii 2.0 Framework)
dmstr/yii2-db                             dev-master 7836531 Database extensions
dmstr/yii2-helpers                        dev-master 8989703 Yii2 Helpers
dmstr/yii2-libs-metapackage               dev-master 891cbd3 Core Library Extensions for Phundament 4 (Yii 2.0 Framework)
dmstr/yii2-log                            0.1.0              SyslogTarget writes log to syslog.
dmstr/yii2-migrate-command                0.2.0              Console Migration Command with multiple paths/aliases support
dmstr/yii2-pages-module                   0.2.0              Application sitemap and navigation manager module for Yii 2.0 Framework
dmstr/yii2-yaml-converter-command         dev-master 9bf2c8e Converts and merges YAML files based on YAML rules
egeloen/http-adapter                      dev-master 3ad0ec8 Issue HTTP request for PHP 5.3+.
evenement/evenement                       dev-master 35e8754 Événement is a very simple event dispatching library for PHP
ezyang/htmlpurifier                       v4.6.0             Standards compliant HTML filter written in PHP
fabpot/php-cs-fixer                       1.11.x-dev 05a6b34 A tool to automatically fix PHP code style
fortawesome/font-awesome                  v4.3.0             The iconic font and CSS framework
frenzelgmbh/cm-activity                   dev-master 5da719e activity module for Yii2
frenzelgmbh/cm-address                    dev-master 41138c1 Common Address Module for yii2
frenzelgmbh/cm-communication              dev-master 60b9923 Common Communication Module for yii2
fzaninotto/faker                          dev-master 56d5ed4 Faker is a PHP library that generates fake data for you.
guzzle/common                             v3.9.2             Common libraries used by Guzzle
guzzle/http                               v3.9.2             HTTP libraries used by Guzzle
guzzle/parser                             v3.9.2             Interchangeable parsers used by Guzzle
guzzle/stream                             v3.9.2             Guzzle stream wrapper component
guzzlehttp/guzzle                         dev-master ef728b6 Guzzle is a PHP HTTP client library
guzzlehttp/promises                       dev-master 97fe721 Guzzle promises library
guzzlehttp/psr7                           1.2.0              PSR-7 message implementation
igorw/get-in                              dev-master e2bfd52 Functions for hash map (assoc array) traversal.
insolita/yii2-adminlte-widgets            v1.1.1             Widgets for AdminLTE theme (Box with remember collapse state, Timeline, Tile, Callout, SmallBox etc)
ivanovyordan/yii2-migration               dev-master 2b94516 Yii 2 composer module migration helper
kartik-v/bootstrap-checkbox-x             v1.5.3             An extended checkbox plugin for bootstrap with three states and additional styles.
kartik-v/bootstrap-fileinput              v4.2.7             An enhanced HTML 5 file input for Bootstrap 3.x with features for file preview for many file types, multiple selection, ajax uploads, a...
kartik-v/bootstrap-popover-x              v1.4.1             Bootstrap Popover Extended - Popover with modal behavior, styling enhancements and more.
kartik-v/bootstrap-star-rating            dev-master 45488aa A simple yet powerful JQuery star rating plugin for Bootstrap.
kartik-v/bootstrap-tabs-x                 v1.3.2             Extended Bootstrap Tabs with ability to align tabs in multiple ways, add borders, rotated titles, and more.
kartik-v/dependent-dropdown               v1.4.3             A multi level dependent dropdown JQuery plugin that allows nested dependencies.
kartik-v/mpdf                             dev-master d48b421 A PHP class to generate PDF files from HTML with Unicode/UTF-8 and CJK support. This is a fork of the official mPDF library.
kartik-v/php-date-formatter               dev-master 7d3dc34 A JQuery datetime formatting and manipulation library using PHP date-time formats in javascript.
kartik-v/yii2-checkbox-x                  dev-master c7c6e64 Extended checkbox widget for bootstrap with three states and additional styles.
kartik-v/yii2-datecontrol                 dev-master 4e858b5 Date control module allowing separation of formats for View and Model for Yii Framework 2.0
kartik-v/yii2-detail-view                 dev-master 6ae616b Various enhancements to the Yii 2 Detail View with multi models, ability to edit data, manage Bootstrap 3 styles and more.
kartik-v/yii2-dynagrid                    v1.4.2             Turbo charge the Yii 2 GridView with personalized columns, page size, and themes.
kartik-v/yii2-editable                    dev-master f9ecdf6 An enhanced editable widget for Yii 2.0 that allows easy editing of displayed data with numerous configuration possibilities.
kartik-v/yii2-grid                        dev-master 913fde8 Yii 2 GridView on steroids. Various enhancements and utilities for the Yii 2.0 GridView widget.
kartik-v/yii2-helpers                     v1.3.2             A collection of useful helper functions for Yii Framework 2.0
kartik-v/yii2-krajee-base                 v1.7.7             Base library and foundation components for all Yii2 Krajee extensions.
kartik-v/yii2-money                       dev-master 3c80908 An advanced money mask input for Yii 2.0 based on jquery maskmoney plugin styled for Bootstrap 3.
kartik-v/yii2-mpdf                        dev-master f65fe85 A Yii2 wrapper component for the mPDF library which generates PDF files from UTF-8 encoded HTML.
kartik-v/yii2-popover-x                   v1.3.1             An extended bootstrap 3.0 popover widget which combines both the bootstrap popover and modal features and includes various new styling ...
kartik-v/yii2-sortable                    dev-master 5d418b8 Create sortable lists and grids using HTML5 drag and drop API for Yii 2.0.
kartik-v/yii2-tabs-x                      dev-master 03eb6db An extended bootstrap 3.0 tabs widget with ability to align tabs in multiple ways, add borders, rotated titles, and more.
kartik-v/yii2-tree-manager                dev-master 78e547e An enhanced tree management module with tree node selection and manipulation using nested sets.
kartik-v/yii2-widget-activeform           v1.4.4             Enhanced Yii2 active-form and active-field with full bootstrap styling support (sub repo split from yii2-widgets).
kartik-v/yii2-widget-affix                dev-master 4e4c88a A scrollspy and affixed enhanced navigation to highlight page sections (sub repo split from yii2-widgets)
kartik-v/yii2-widget-alert                dev-master 5706274 A widget to generate alert based notifications using bootstrap-alert plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-colorinput           dev-master 907fd10 An enhanced Yii 2 widget encapsulating the HTML 5 color input (sub repo split from yii2-widgets)
kartik-v/yii2-widget-datepicker           dev-master f9ee0fd Enhanced Yii2 wrapper for the bootstrap datepicker plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widget-datetimepicker       dev-master 6fff3db Enhanced Yii2 wrapper for the bootstrap datetimepicker plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-depdrop              dev-master 40bbe95 Widget that enables setting up dependent dropdowns with nested dependencies (sub repo split from yii2-widgets)
kartik-v/yii2-widget-fileinput            dev-master 084447f An enhanced FileInput widget for Bootstrap 3.x with file preview, multiple selection, and more features (sub repo split from yii2-widgets)
kartik-v/yii2-widget-growl                dev-master c79abaa A widget to generate growl based notifications using bootstrap-growl plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-rangeinput           dev-master 38dd7c6 An enhanced Yii 2 widget encapsulating the HTML 5 range input (sub repo split from yii2-widgets)
kartik-v/yii2-widget-rating               dev-master 8cef838 A Yii2 widget for the simple yet powerful bootstrap-star-rating plugin with fractional rating support (sub repo split from yii2-widgets)
kartik-v/yii2-widget-select2              dev-master e72880e Enhanced Yii2 wrapper for the Select2 jQuery plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widget-sidenav              dev-master 54186e7 An enhanced side navigation menu styled for bootstrap (sub repo split from yii2-widgets)
kartik-v/yii2-widget-spinner              dev-master c39f734 A widget to render animated CSS3 loading spinners with VML fallback for IE (sub repo split from yii2-widgets)
kartik-v/yii2-widget-switchinput          dev-master c3bc211 A Yii2 wrapper widget for the Bootstrap Switch plugin to use checkboxes & radios as toggle switchinputes (sub repo split from yii2-widg...
kartik-v/yii2-widget-timepicker           dev-master b6538d1 Enhanced Yii2 wrapper for the bootstrap timepicker plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-touchspin            dev-master f41a1fe A Yii2 wrapper widget for the Bootstrap Switch plugin to use checkboxes & radios as toggle touchspines (sub repo split from yii2-widgets)
kartik-v/yii2-widget-typeahead            dev-master b0c2ee4 Enhanced Yii2 wrapper for the Twitter Typeahead plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widgets                     dev-master b7eb849 Collection of useful widgets for Yii Framework 2.0 extending functionalities for Bootstrap
lajax/yii2-translate-manager              1.4.9              Online Translate
league/period                             dev-master 4c4b7f1 A time range immutable value object
mikehaertl/php-shellcommand               1.1.0              An object oriented interface to shell commands
mikevanriel/text-to-latex                 1.0.0              A converter class that converts normal ASCII text to valid LaTeX
neitanod/forceutf8                        dev-master 2c1b21e PHP Class Encoding featuring popular Encoding::toUTF8() function --formerly known as forceUTF8()-- that fixes mixed encoded strings.
nikic/php-parser                          0.9.x-dev ef70767  A PHP parser written in PHP
open-ecommerce/yii2-backuprestore         dev-master 1ea6e80 Database Backup and Restore functionality
philippfrenzel/yii2-textareaautosize      dev-master 3b56b48 Yii2 textareaautosize Widgets
philippfrenzel/yii2feedback               dev-master 221a00e Yii2 feedback js Widgets
philippfrenzel/yii2fullcalendar           dev-master 04bfbb7 Yii2 fullcalendar Widgets
philippfrenzel/yii2slidebars              dev-master 375e64a jquery slidebars extension for yii
philippfrenzel/yii2tooltipster            dev-master c58fab8 Yii2 tooltipster Integration
philippfrenzel/yii2visjs                  dev-master abbad72 Yii2 visjs Widgets
phpdocumentor/reflection                  dev-master fc40c3f Reflection library to do Static Analysis for PHP Projects
phpdocumentor/reflection-docblock         2.0.4              
phpoffice/phpword                         dev-master 38cb04d PHPWord - A pure PHP library for reading and writing word processing documents (DOCX, ODT, RTF, HTML, PDF)
phpspec/php-diff                          dev-master 30e103d A comprehensive library for generating differences between two hashable objects (strings or arrays).
psr/http-message                          dev-master 85d6369 Common interface for HTTP messages
psr/log                                   dev-master 9e45edc Common interface for logging libraries
raoul2000/yii2-workflow                   dev-master e8111c4 A simple workflow engine for Yii2
raoul2000/yii2-workflow-view              dev-master 0ea0b90 A simple widget to display your workflows
react/event-loop                          v0.4.1             Event loop abstraction layer that libraries can use for evented I/O.
react/socket                              dev-master 9b3eba6 Library for building an evented socket server.
react/stream                              v0.4.2             Basic readable and writable stream interfaces that support piping.
rmrevin/yii2-fontawesome                  2.9.2              Asset Bundle for Yii2 with Font Awesome
schmunk42/retry                           dev-master 6a8486d A tiny library for retrying failing operations. [fork with tags]
schmunk42/yii2-giiant                     dev-master fbb00f5 Gii CRUD generator for Yii 2 Framework
schmunk42/yii2-markdocs-module            dev-master 9154df1 Renders markdown files from local folder as views
sebastian/diff                            dev-master 6899b3e Diff implementation
squizlabs/php_codesniffer                 dev-master dee5d3e PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
swiftmailer/swiftmailer                   5.x-dev 6522539    Swiftmailer, free feature-rich PHP mailer
symfony/console                           2.8.x-dev 93c0bce  Symfony Console Component
symfony/event-dispatcher                  2.8.x-dev e79162f  Symfony EventDispatcher Component
symfony/filesystem                        2.8.x-dev 287fc0b  Symfony Filesystem Component
symfony/finder                            2.8.x-dev 142440d  Symfony Finder Component
symfony/http-foundation                   2.8.x-dev ff8b122  Symfony HttpFoundation Component
symfony/process                           2.8.x-dev fc18e37  Symfony Process Component
symfony/routing                           2.8.x-dev 2bc066c  Symfony Routing Component
symfony/stopwatch                         2.8.x-dev 9eb95ce  Symfony Stopwatch Component
symfony/yaml                              2.8.x-dev d196cb1  Symfony Yaml Component
vlucas/phpdotenv                          1.1.x-dev 0cac554  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
willdurand/geocoder                       v3.0.0-alpha2      The almost missing Geocoder PHP 5.4 library.
xj/yii2-modernizr-widget                  dev-master 3444217 yii2-modernizr-widget
yiisoft/yii2                              dev-master 42749cb Yii PHP Framework Version 2
yiisoft/yii2-apidoc                       dev-master eee2700 API Documentation generator for the Yii framework 2.0
yiisoft/yii2-authclient                   dev-master e8c639a External authentication via OAuth and OpenID for the Yii framework
yiisoft/yii2-bootstrap                    dev-master 5ae1277 The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-codeception                  dev-master 4428504 The Codeception integration for the Yii framework
yiisoft/yii2-coding-standards             2.0.1              Yii PHP Framework Version 2 - Coding standard tools
yiisoft/yii2-composer                     dev-master 6b2a2b3 The composer plugin for Yii extension installer
yiisoft/yii2-debug                        2.0.5              The debugger extension for the Yii framework
yiisoft/yii2-faker                        dev-master 091bc3c Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                          dev-master 6519954 The Gii extension for the Yii framework
yiisoft/yii2-jui                          dev-master 7b71a03 The Jquery UI extension for the Yii framework
yiisoft/yii2-swiftmailer                  dev-master fffcd50 The SwiftMailer integration for the Yii framework
zendframework/zend-diactoros              1.1.x-dev e268dd5  PSR HTTP Message implementations

**Comment by schmunk42** [comment]
You're using 1.1.x-dev:

    vlucas/phpdotenv                          1.1.x-dev 0cac554  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.

I'd recommend to switch to a stable version. The current syntax in Phundament is for phpdotenv 2.x.

**Comment by philippfrenzel** [comment]
ok, my fault, had both versions defined in composer… so it took the lower one… now it’s working… :/ thanks!

**Pull request closed without merging**
